### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Tamir198** [zakodium/react-mf#13]
Hey, on the npm page when clicking:

![image](https://user-images.githubusercontent.com/34707669/189055853-83793792-1550-4239-a23c-f116ba466418.png)

I am receiving 404 page:

![image](https://user-images.githubusercontent.com/34707669/189055909-27fe8486-642e-444c-9da2-c42b95384974.png)

**Comment by stropitek** [comment]
The url is outdated on npm but is up to date in the readme.

https://zakodium-oss.github.io/react-mf/

The npm page will be fixed next time there is a release

**Comment by targos** [comment]
released
