### ISSUE TITLE
Storybook build broken on GH pages

### ISSUE THREAD

**Issue by targos** [zakodium/react-mf#17]
https://zakodium-oss.github.io/react-mf/

![CleanShot 2023-04-24 at 11 43 25](https://user-images.githubusercontent.com/2352663/233960716-87dd7949-85d5-4abc-9d0e-73f418889f22.png)

**Comment by tpoisseau** [comment]
Hum, It's weird.
It works well on my windows computer and on my mac. (with node 16 and 20).

After a deeper lookup, it seems to be related with github pages routing.

- https://zakodium-oss.github.io/react-mf/assets/_commonjsHelpers-042e6b4d.js
- https://zakodium-oss.github.io/react-mf/assets/_getPrototype-9db2bfe0.js

Returns 404 error. But they exist in repo :

- https://github.com/zakodium-oss/react-mf/blob/gh-pages/assets/_commonjsHelpers-042e6b4d.js
- https://github.com/zakodium-oss/react-mf/blob/gh-pages/assets/_getPrototype-9db2bfe0.js

All others files in build seems to be properly returned by github pages. The only difference I see between theses 2 files is they start by `_` underscore. Maybe github a special configuration for this kind of file ?

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-from-a-branch

> Your GitHub Pages site will always be deployed with a GitHub Actions workflow run, even if you've configured your GitHub Pages site to be built using a different CI tool. Most external CI workflows "deploy" to GitHub Pages by committing the build output to the gh-pages branch of the repository, and typically include a .nojekyll file. When this happens, the GitHub Actions workflow will detect the state that the branch does not need a build step, and will execute only the steps necessary to deploy the site to GitHub Pages servers.

May you shall add a `.nojekyll` to avoid extra steps from github ?

**Comment by targos** [comment]
> May you shall add a `.nojekyll` to avoid extra steps from github ?

Indeed, good find!

**Comment by targos** [comment]
Fixed in https://github.com/zakodium-oss/react-mf/commit/0290554dc8670e68a84d53807d870d9732e7ea9e
